### ISSUE TITLE
Create an Interactive Readme.md

### ISSUE THREAD

**Issue by stephin007** [stephin007/myportfolio#13]
Need an interactive readme.md, which includes badges, screenshots etc.

**Comment by MinerBigWhale** [comment]
Could you please indicate what you mean by "interractive" ?
Would you mean "attractive" ?
For an attractive Readme, you can Assign me 😉

**Comment by stephin007** [comment]
@MinerBigWhale anything which you understood! 🌟
Assigning u the task

**Comment by MinerBigWhale** [comment]
I Create a PR for this, hope you will love it 😉

**Comment by stephin007** [comment]
checking it @MinerBigWhale

**Comment by stephin007** [comment]
@MinerBigWhale thank you for contributing to the project,
Please check out my other open projects

**Comment by MinerBigWhale** [comment]
Thank you @stephin007, wish you the best for the next
