### ISSUE TITLE
i don't see a Contact Me section, I can build that for you in React. 

### ISSUE THREAD

**Issue by Siddharth009** [stephin007/myportfolio#16]
I will build the UI and later you can connect that with your gmail.

**Comment by stephin007** [comment]
Hey @Siddharth009 
Do you mean a contact form?

**Comment by Siddharth009** [comment]
Yes

**Comment by Siddharth009** [comment]
> Hey @Siddharth009
> Do you mean a contact form?

Yes

**Comment by stephin007** [comment]
Okay, sure @Siddharth009 but before rasing any PR,
send me a screenshot of your work!

**Comment by stephin007** [comment]
@Siddharth009 any progress?

**Comment by stephin007** [comment]
@Siddharth009 If you dont respond, i will have to close this issue :)
