### ISSUE TITLE
Tests are missing on all components

### ISSUE THREAD

**Issue by nok91** [stephin007/myportfolio#17]
Tests missing for following components:

- [ ] About,js
- [ ] Contact.js
- [ ] Home.js
- [ ] Navbar.js
- [ ] Project.js

**Comment by stephin007** [comment]
What do you have in mind? @nok91 
Let me know, what will you be doing!

**Comment by nok91** [comment]
With your permission, I would like to add tests to those files! @stephin007  ;) 

- [ ]  About.test,js
- [ ]  Contact.test.js
- [ ]  Home.test.js
- [ ]  Navbar.test.js
- [ ]  Project.test.js

**Comment by stephin007** [comment]
@nok91 please go ahead...brother!
Few points to note:

1. Don't clone directly from my repo.
2. Fork my repo and then clone it
3. Create a branch, whose naming convention must be: <username>/testcase/<fileName>
You should create a different branch for test cases in different files.

Rest if you still have any queries, please mailme at : mail@stephinreji.me, if i dont respond here

**Comment by stephin007** [comment]
Leave a 🌟 if you like the project

**Comment by stephin007** [comment]
@nok91 please pull the latest code, i have done some changes!
