### ISSUE TITLE
Need a dark theme switcher

### ISSUE THREAD

**Issue by stephin007** [stephin007/myportfolio#20]
Well the title says it all.
A switch which switches the light mode to a cool night mode.

**Comment by chinmaym07** [comment]
Hey @stephin007  can I try this .. ?

**Comment by stephin007** [comment]
Hey @chinmaym07 , thankyou for showing interest, please go ahead.
But before starting please go through this link , it has the instructions on how to raise PR on open source projects. If you already know it, then never mind my statement 😄

**Comment by stephin007** [comment]
@chinmaym07 any progress with this?

**Comment by chinmaym07** [comment]
Hey @stephin007 I am working on it and will try to submit pr asap. :+1:

**Comment by stephin007** [comment]
@chinmaym07 any progress yet?

**Comment by chinmaym07** [comment]
Yes . I have done some part of that. 
I will surely try to submit the PR by today. :+1:

**Comment by stephin007** [comment]
Sure, @chinmaym07

**Comment by chinmaym07** [comment]
I have tried this. Please check
![Screen Shot 2020-11-24 at 21 31 05](https://user-images.githubusercontent.com/44670961/100119097-7fde8f00-2e9c-11eb-9ac5-d7962d358113.png)
![Screen Shot 2020-11-24 at 21 30 55](https://user-images.githubusercontent.com/44670961/100119101-810fbc00-2e9c-11eb-864f-ca4ce4f67945.png)

**Comment by stephin007** [comment]
@chinmaym07 yes please do!

**Comment by stephin007** [comment]
And @chinmaym07  please right align the switch to the left of the hamburger icon

**Comment by chinmaym07** [comment]
I have opened a pr #21.

**Comment by stephin007** [comment]
Thanks for working on this project @chinmaym07 your PR is merged now!
Please do leave a star to this repo!
you can check out my other projects if you get time and leave a star there also
