### ISSUE TITLE
Create an Interactive Readme.md

### ISSUE THREAD

**Issue by stephin007** [stephin007/myportfolio#4]
Need to Remove all the existing Readme.md and make an intercative one, its basically a portfolio

**Comment by liamortiz** [comment]
Hello I'm interested in tackling this issue. Can you elaborate a bit ?

**Comment by LuizHAP** [comment]
@stephin007 what i think about https://github.com/LuizHAP/proffy/blob/master/README.md?

**Comment by stephin007** [comment]
@liamortiz yes, pleas go ahead.
To get more info you can check the link in the about its an portfolio, 
Its tech stack would be on react  fully responsie with dynamic page routing(i.e. website does not reload when we change to different pages)

**Comment by stephin007** [comment]
> @stephin007 what i think about https://github.com/LuizHAP/proffy/blob/master/README.md?

@LuizHAP is this link a reference, which you are going to make?

**Comment by LuizHAP** [comment]
> > @stephin007 what i think about https://github.com/LuizHAP/proffy/blob/master/README.md?
> 
> @LuizHAP is this link a reference, about what you are going to make?

Yes, it's a reference, did you like the styling?

**Comment by stephin007** [comment]
@LuizHAP Please go ahead

**Comment by stephin007** [comment]
@LuizHAP any progress??

**Comment by stephin007** [comment]
@LuizHAP since you did not respond I am closing this issue
