### ISSUE TITLE
Make all the data in the portfolio dynamic

### ISSUE THREAD

**Issue by stephin007** [stephin007/myportfolio#5]
If you check the portfolio link provided in the about section, you will see all the data is static and i want all the data which is their inside about section, projects section to be taken in separate files as JSON and store them locally and rendering them in one single component.

**Comment by elicavalheiro** [comment]
Hi, @stephin007! I would like to try help on this issue. If you want to, can you please assign me? :D

**Comment by stephin007** [comment]
Great, @elicavalheiro please do! But let me know what will be your approach

**Comment by elicavalheiro** [comment]
Of course @stephin007! Let me tell the steps:
1. Create the JSON file, I suggest to create a new folder called data to concentrate all the JSON files of your project, on this case we could create a about.json and put all the static info on this file
2. Import the about.json file into About component (we can simply do this by using import ... from ...)
3. Manipulate our json on the page (by these point, we will have something alike a HTTP response)

**Comment by stephin007** [comment]
Great 🔥, please go ahead!

**Comment by stephin007** [comment]
Hey @elicavalheiro , Any progress till now???

**Comment by stephin007** [comment]
CLosing the issue since no response from the contributer
