### ISSUE TITLE
Make all the data in the portfolio dynamic.

### ISSUE THREAD

**Issue by stephin007** [stephin007/myportfolio#7]
If you check the portfolio link provided in the about section, you will see all the data is static and i want all the data which is their inside about section, projects section to be taken in separate files as JSON and store them locally and rendering them in one single component.

**Comment by ZenVega** [comment]
hi, i would give it a shot. would u assign this to me?

**Comment by stephin007** [comment]
Sure, @ZenVega please do, i hope you understood the issue!

**Comment by krishnaraj-e** [comment]
Hey, the static data is kinda messy. Would it be okay if i just set up a connection and change some sample things?

**Comment by stephin007** [comment]
Hi @krishnaraj-e yes , i know right, please do whatever you feel is right! and alsonplease let me know what you are intending to do! 🌟

**Comment by ZenVega** [comment]
sure, I think I got know what's the issue. I haven't checked the code yet, though but i will tomorrow.

**Comment by stephin007** [comment]
@ZenVega closing the issue, thank you for the contribution
